[package]
name = "AccessControl"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache-2.0"            
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     

[dependencies]

[addresses]
access_control = "0x0"

