[package]
name = "InterestAccessControl"
edition = "2024.beta"
license = "Apache-2.0"            
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     

[dependencies]

[addresses]
interest_access_control = "0x1"

