[package]
name = "Interest Math"
edition = "2024.beta"
license = "Apache-2.0"            
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]    

[dependencies]

[addresses]
interest_math = "0x0"