[package]
name = "InterestPriceOracle"
edition = "2024.beta"
license = "Apache-2.0"            
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]    

[dependencies]
interest_access_control = { r.mvr = "@interest/acl" }
interest_math = { r.mvr = "@interest/math" }

[addresses]
interest_price_oracle = "0x0"

[r.mvr]
network = "testnet"
